<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-4ANV6G9N" failures="2" tests="3" name="Test" time="89.688" errors="0" timestamp="2022-03-28T15:50:01 IST">
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanLogin" time="38.712"/>
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanAddNewAddress" time="14.928">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at TestClasses.AddNewAddress.verifyUserCanAddNewAddress(AddNewAddress.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanAddNewAddress -->
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanAddNewAddress" time="5.437">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at TestClasses.AddNewAddress.verifyUserCanAddNewAddress(AddNewAddress.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanAddNewAddress -->
</testsuite> <!-- Test -->
